### PR TITLE
Allow easier installation into other directories

### PR DESCRIPTION
**Pull request by hecon5**
In our environment, we have to install the thing in a different location. This allows for some customization to allow for that. It doesn't magically make the ribbon work, but it's a step in the right direction.

### CODE REVIEW

**Comment by hecon5** [comment]
Wondering if instead of using constants, it may be better to just use a Folder Picker, which could be also be triggered by a `VCS` api. This would allow me to have it deployed on our dev's machines along with the other dev tools we use, and even perhaps as a ride along for our ClickOnce package... (go into Admin page and click "InstallVCS" and it would deploy it).

**Comment by hecon5** [comment]
@joyfullservice, this is ready for review. I tried to unify all install folder routines to make moving the directory in the future easier, as well as allow users who have to move the install for various reasons (security settings for me, anyway). 

This also added a way to find the install folder (useful for hotpatching and / or just knowing where things are).

let me know what you think!

**Comment by hecon5** [comment]
> Would you potentially be able to load the COM add-in (ribbon) if the add-in and the DLL were located in a more trusted folder?

Maybe...I'm still testing that. It seems to work "kind of". There appear to be two different security hurdles, and the COM addin is the next hurdle for us. This PR started when we noticed new devs couldn't install anymore, but if we put it in an already trusted location (we have a trusted folder for deployment we already negotiated), it did work. Originally, I had a bunch of different new Constants, but having a common registry stored property (just like the `TrustVCS Install Folder` we added previously) seemed to be the far better (and least disruptive to most users) approach. The two constants we left was to make it clearer to other devs (and users who are extremely curious) what's going on in the code and avoid hard-coded folder paths (there may come a day we need to move this to "MSAccessVCS2" or something and having one location to change it will make life easier instead of chasing down tons of legacy instance).

For now, this will simply allow us to even run the thing for new devs; the COM addin is giving other errors (which may or may not be solved by this), so I wanted to break the PRs into two pieces so I didn't get /too/ jumbled up and could keep focused on each element separately.

>  optional environment variable to override the default location 

Actually, that's the intent behind the `modInstall.VCSInstallFolder` Parameter: a common parameter that defaults to the location for 99% of users, but will persist through installs for those of us who must move the location for various reasons. 

I wanted to make it a semi-hidden function (install screen is just a text box), and a "show me the folder" on the options location, as I didn't think most people would want (or even should) move this (as it is extremely touchy if you install two versions in different folders; the Addin links get upset and break entirely).

Screenshots for reference: 
image

image

**Comment by joyfullservice** [comment]
Thanks for the additional background. I assume the negotiated deployment folder is on the local development machines, not a network share... (I am pretty sure this would be the case, but just wanted to verify.)

I just made a small change to the twinBasic project to use a relative path for the Access add-in location, instead of hard-coding the default location. You can grab the updated DLL from the source folder on the dev branch. I would be curious to hear if the ribbon works for you after this change, now that it can run from an alternate installation folder.

**Comment by hecon5** [comment]
Still blocked, but I haven't restarted yet. Sometimes that's the issue, but not holding my breath (yet).

**Comment by hecon5** [comment]
Follow up after reboot. COM addin is still a no-go for now. Getting same error I was in #358

**Comment by hecon5** [comment]
@joyfullservice bump

**Comment by hecon5** [comment]
@joyfullservice : this is limiting our ability to use v4 (especially with the VSTO addin). 

Any way we can get this incorporated? I see there are now conflicts with this PR, so I can look into resolving those, unless you've got a different way to incorporate the way to install to various locations?

**Comment by joyfullservice** [comment]
Just a question on this... Have you been able to prototype V4 working in a custom install folder? Just weighing the value vs. complexity balance.  😄 Ideally, if you can get to the point where "yes, this works" in your environment, then we can look at incorporating something into the main code base to try to accommodate the requirements.

**Comment by hecon5** [comment]
It's been a while since I tried, (back then I was running into other VSTO issues but I can rebuild the thing and see if it will run in our folders. 
Since I have a decent understanding on what parts talk to builtin paths, I can at least kludge a test.

The other thing is: I cannot seem to build the latest V4 from either V3 or V4 (or the version I'd been running previously). Is there a chance you can build the latest for me and I can give that a go?

**Comment by joyfullservice** [comment]
Sure, attached is a build from the current `dev` branch.
[Version Control_v4.0.10(beta).zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/11325890/Version.Control_v4.0.10.beta.zip)

Also, just to clarify, the ribbon is an ActiveX COM DLL, but not a VSTO build. It was compiled through twinBASIC and should be lighter weight and more robust than a VSTO add-in.

Hope that helps!

**Comment by hecon5** [comment]
Thanks! I'll give this a go!

**Comment by hecon5** [comment]
Also, just caught that this is a COM DLL Addin: this may be the culprit if it is not signed. I'll do some digging and see if I can make it work in our trusted location first.

**Comment by hecon5** [comment]
Ok, @joyfullservice : I got the latest version to build, export, and function with the exception of the COM addin. Because it's not signed, my security settings won't let it load no matter where it is. 

That said: the alternate install works, and allows the addin to be loaded and operate in our environment's specified "trusted location", which is a huge thing. 

I need to figure out how to address the COM DLL Error, and we'd be back in business:

image
image

**Comment by hecon5** [comment]
I'm going to rebase these from the new fork, this will hopefully keep things tidier.

**Comment by hecon5** [comment]
Closing to create new merge request from a different fork.

**Pull request closed without merging**
