### PR TITLE
Add custom install option

### PR DESCRIPTION
**Pull request by hecon5**
This is a rebuild of #361 now that the fork was split.

### CODE REVIEW

**Comment by hecon5** [comment]
@joyfullservice  This is ready for checking and inclusion; If you would be so kind as to take a peek and merge or let me know if there are other fixes, that's be great, I'd like to have my team start using 4.x, and this will let them do it.

**Comment by joyfullservice** [comment]
Thanks for your work on this! There are a few tweaks I will probably make, (which has been the main holdup for me) but I will see if I can get this worked through in the next several days. I am excited about your team getting to move to version 4.  😄

**Comment by hecon5** [comment]
Super, looking forward to it!

**Comment by joyfullservice** [comment]
Do you mind if I commit directly to this PR? I just want to make sure that when I merge it into dev, it is ready to go and doesn't leave anything hanging out there that might trip up other users that are regularly building the dev branch.

**Comment by hecon5** [comment]
No; I think that'll be fine; will also let me see what you change (curiosity's sake), and I'm personally a fan of avoiding commits directly to `dev` anyway.

**Comment by joyfullservice** [comment]
I made some progress on this today, and will plan to pick it up again as I have opportunity next week. As you will see in the following screenshots, I spent most of my time on the user interface, changing the install form to use a tab control so we can optionally display the more advanced installation settings. This helps keep things very simple for most users, while still providing those more advanced options for those that need/require those.

image

From the basic install page, you simply click the navigation link to switch to the advanced install screen.

image

Again, I haven't wired these up to the rest of the code, but I like the cleaner user experience with this approach.

**Comment by joyfullservice** [comment]
I reworked the UI a little further to use a checkbox instead of the navigation link. This seems to look nicer from a design standpoint and is possibly slightly more intuitive for the user.

image

image

**Comment by hecon5** [comment]
I like that better, too. Cleaner. 

I was thinking about that "trust Addin folder" option; should we move that to the install options, and just call it "Install Options" instead of "advanced"? That way, the default options are selected normally, but the user can alter them, just like an actual installer?

**Comment by joyfullservice** [comment]
Made a bunch of progress on this today. Hoping to finish it up tomorrow...

**Comment by joyfullservice** [comment]
Okay, I have finished a pretty significant rework of the installer system. You will see a bunch of commits coming through as I document various changes...

**Comment by hecon5** [comment]
Cool, I'm going to build this and let you know, thanks!

**Comment by joyfullservice** [comment]
Sounds good! Make sure you catch that additional commit in `dev` to fix the options json file.

**Pull request merged**
